### ISSUE TITLE
auto renew经常报错

### ISSUE THREAD

**Issue by SoraKasvgano** [CokeMine/EUserv_extend#25]
经尝试第一天可以第二天不行第三天又可以。。。。

Run python main.py
Traceback (most recent call last):
******************************
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
正在续费第 1 个账号
    httplib_response = self._make_request(
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/EUserv_extend/EUserv_extend/main.py", line 123, in <module>
    sessid, s = login(user_list[i], passwd_list[i])
  File "/home/runner/work/EUserv_extend/EUserv_extend/main.py", line 30, in login
    f = session.post(url, headers=headers, data=login_data)
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Error: Process completed with exit code 1.

**Comment by CokeMine** [comment]
#23 手动登陆一下账号，看看是不是需要确认一下个人信息？

**Comment by SoraKasvgano** [comment]
> #23 手动登陆一下账号，看看是不是需要确认一下个人信息？

没有出现，比较奇怪emmm，但是仍但出错。

**Comment by if1y** [comment]
刚才我也出现了一次超时失败。正准备来提 issue。看来我不是个例。

2号才刚刚登录并确认个人信息……
也就是说，只间隔了昨天一天……

**Comment by CokeMine** [comment]
> > #23 手动登陆一下账号，看看是不是需要确认一下个人信息？
> 
> 没有出现，比较奇怪emmm，但是仍但出错。



> 刚才我也出现了一次超时失败。正准备来提 issue。看来我不是个例。
> 
> 2号才刚刚登录并确认个人信息……
> 也就是说，只间隔了昨天一天……

有可能真的是0:50(GMT)这个时间同时运行的太多了。https://github.com/CokeMine/EUserv_extend/issues/23#issuecomment-753312984

**Comment by CokeMine** [comment]
@SoraKasvgano 尝试在Action界面Re-run一下报错的几个workflows？康康会不会出问题。

**Comment by if1y** [comment]
此刻手动执行正常，确实很有可能是集中任务导致的问题。
