### ISSUE TITLE
VPS下，WARP网络下报错。

### ISSUE THREAD

**Issue by YG-tsj** [cokemine/EUserv_extend#84]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fd767ad3250>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='support.euserv.com', port=443): Max retries exceeded with url: /index.iphp (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd767ad3250>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main3.py", line 191, in <module>
    sessid, s = login(user_list[i], passwd_list[i])
  File "main3.py", line 48, in login
    sess = session.get(url, headers=headers)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='support.euserv.com', port=443): Max retries exceeded with url: /index.iphp (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd767ad3250>: Failed to establish a new connection: [Errno 110] Connection timed out'))

**Comment by YG-tsj** [comment]
这前可以，突然这几天就报错了。。

**Comment by YG-tsj** [comment]
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='support.euserv.com', port=443): Max retries exceeded with url: /index.iphp
感觉这句话是关键，作者麻烦看下

**Comment by layou233** [comment]
草了，我也一直是用euserv的机子挂cron续euserv，也用的warp，这几天也炸了  
自己折腾了一下，改了一下UA，设了timeout到一个巨大的数，发现都无效，我也正在寻找解决办法

**Comment by layou233** [comment]
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='support.euserv.com', port=443): Max retries exceeded with url: /index.iphp
> 感觉这句话是关键，作者麻烦看下

主要是`[Errno 110] Connection timed out`  
你提到的这个是requests里默认的5次重试，然后5次重试都失败报的错，导致失败的根本原因是这个莫名其妙的超时  
我对euserv的网站系统没有研究，但我怀疑这个超时可能是一种类似于防CC的盾？直接把可疑流量屏蔽了？

**Comment by YG-tsj** [comment]
> > requests.exceptions.ConnectionError: HTTPSConnectionPool(host='support.euserv.com', port=443): Max retries exceeded with url: /index.iphp
> > 感觉这句话是关键，作者麻烦看下
> 
> 主要是`[Errno 110] Connection timed out`
> 你提到的这个是requests里默认的5次重试，然后5次重试都失败报的错，导致失败的根本原因是这个莫名其妙的超时
> 我对euserv的网站系统没有研究，但我怀疑这个超时可能是一种类似于防CC的盾？直接把可疑流量屏蔽了？

那看来是无解了！！
